apiVersion: v1
kind: ConfigMap
metadata:
  name: ordersystem-config
  namespace: ordersystem
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  NotificationsUrl: "http://notifications-api-svc"
